name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Check project imports
        run: |
          python -m py_compile api/app.py
          python -m py_compile training/train_model.py
